export const SURAHS = [
  { number: 1, name: 'الفاتحة', versesCount: 7, startPage: 1, type: 'مكية' },
  { number: 2, name: 'البقرة', versesCount: 286, startPage: 2, type: 'مدنية' },
  { number: 3, name: 'آل عمران', versesCount: 200, startPage: 50, type: 'مدنية' },
  { number: 4, name: 'النساء', versesCount: 176, startPage: 77, type: 'مدنية' },
  { number: 5, name: 'المائدة', versesCount: 120, startPage: 106, type: 'مدنية' },
  { number: 6, name: 'الأنعام', versesCount: 165, startPage: 128, type: 'مكية' },
  { number: 7, name: 'الأعراف', versesCount: 206, startPage: 151, type: 'مكية' },
  { number: 8, name: 'الأنفال', versesCount: 75, startPage: 177, type: 'مدنية' },
  { number: 9, name: 'التوبة', versesCount: 129, startPage: 187, type: 'مدنية' },
  { number: 10, name: 'يونس', versesCount: 109, startPage: 208, type: 'مكية' },
  { number: 11, name: 'هود', versesCount: 123, startPage: 221, type: 'مكية' },
  { number: 12, name: 'يوسف', versesCount: 111, startPage: 235, type: 'مكية' },
  { number: 13, name: 'الرعد', versesCount: 43, startPage: 249, type: 'مدنية' },
  { number: 14, name: 'إبراهيم', versesCount: 52, startPage: 255, type: 'مكية' },
  { number: 15, name: 'الحجر', versesCount: 99, startPage: 262, type: 'مكية' },
  { number: 16, name: 'النحل', versesCount: 128, startPage: 267, type: 'مكية' },
  { number: 17, name: 'الإسراء', versesCount: 111, startPage: 282, type: 'مكية' },
  { number: 18, name: 'الكهف', versesCount: 110, startPage: 293, type: 'مكية' },
  { number: 19, name: 'مريم', versesCount: 98, startPage: 305, type: 'مكية' },
  { number: 20, name: 'طه', versesCount: 135, startPage: 312, type: 'مكية' },
  { number: 21, name: 'الأنبياء', versesCount: 112, startPage: 322, type: 'مكية' },
  { number: 22, name: 'الحج', versesCount: 78, startPage: 332, type: 'مدنية' },
  { number: 23, name: 'المؤمنون', versesCount: 118, startPage: 342, type: 'مكية' },
  { number: 24, name: 'النور', versesCount: 64, startPage: 350, type: 'مدنية' },
  { number: 25, name: 'الفرقان', versesCount: 77, startPage: 359, type: 'مكية' },
  { number: 26, name: 'الشعراء', versesCount: 227, startPage: 367, type: 'مكية' },
  { number: 27, name: 'النمل', versesCount: 93, startPage: 377, type: 'مكية' },
  { number: 28, name: 'القصص', versesCount: 88, startPage: 385, type: 'مكية' },
  { number: 29, name: 'العنكبوت', versesCount: 69, startPage: 396, type: 'مكية' },
  { number: 30, name: 'الروم', versesCount: 60, startPage: 404, type: 'مكية' },
  { number: 31, name: 'لقمان', versesCount: 34, startPage: 411, type: 'مكية' },
  { number: 32, name: 'السجدة', versesCount: 30, startPage: 415, type: 'مكية' },
  { number: 33, name: 'الأحزاب', versesCount: 73, startPage: 418, type: 'مدنية' },
  { number: 34, name: 'سبأ', versesCount: 54, startPage: 428, type: 'مكية' },
  { number: 35, name: 'فاطر', versesCount: 45, startPage: 434, type: 'مكية' },
  { number: 36, name: 'يس', versesCount: 83, startPage: 440, type: 'مكية' },
  { number: 37, name: 'الصافات', versesCount: 182, startPage: 446, type: 'مكية' },
  { number: 38, name: 'ص', versesCount: 88, startPage: 453, type: 'مكية' },
  { number: 39, name: 'الزمر', versesCount: 75, startPage: 458, type: 'مكية' },
  { number: 40, name: 'غافر', versesCount: 85, startPage: 467, type: 'مكية' },
  { number: 41, name: 'فصلت', versesCount: 54, startPage: 477, type: 'مكية' },
  { number: 42, name: 'الشورى', versesCount: 53, startPage: 483, type: 'مكية' },
  { number: 43, name: 'الزخرف', versesCount: 89, startPage: 489, type: 'مكية' },
  { number: 44, name: 'الدخان', versesCount: 59, startPage: 496, type: 'مكية' },
  { number: 45, name: 'الجاثية', versesCount: 37, startPage: 499, type: 'مكية' },
  { number: 46, name: 'الأحقاف', versesCount: 35, startPage: 502, type: 'مكية' },
  { number: 47, name: 'محمد', versesCount: 38, startPage: 507, type: 'مدنية' },
  { number: 48, name: 'الفتح', versesCount: 29, startPage: 511, type: 'مدنية' },
  { number: 49, name: 'الحجرات', versesCount: 18, startPage: 515, type: 'مدنية' },
  { number: 50, name: 'ق', versesCount: 45, startPage: 518, type: 'مكية' },
  { number: 51, name: 'الذاريات', versesCount: 60, startPage: 520, type: 'مكية' },
  { number: 52, name: 'الطور', versesCount: 49, startPage: 523, type: 'مكية' },
  { number: 53, name: 'النجم', versesCount: 62, startPage: 526, type: 'مكية' },
  { number: 54, name: 'القمر', versesCount: 55, startPage: 528, type: 'مكية' },
  { number: 55, name: 'الرحمن', versesCount: 78, startPage: 531, type: 'مدنية' },
  { number: 56, name: 'الواقعة', versesCount: 96, startPage: 534, type: 'مكية' },
  { number: 57, name: 'الحديد', versesCount: 29, startPage: 537, type: 'مدنية' },
  { number: 58, name: 'المجادلة', versesCount: 22, startPage: 542, type: 'مدنية' },
  { number: 59, name: 'الحشر', versesCount: 24, startPage: 545, type: 'مدنية' },
  { number: 60, name: 'الممتحنة', versesCount: 13, startPage: 549, type: 'مدنية' },
  { number: 61, name: 'الصف', versesCount: 14, startPage: 551, type: 'مدنية' },
  { number: 62, name: 'الجمعة', versesCount: 11, startPage: 553, type: 'مدنية' },
  { number: 63, name: 'المنافقون', versesCount: 11, startPage: 554, type: 'مدنية' },
  { number: 64, name: 'التغابن', versesCount: 18, startPage: 556, type: 'مدنية' },
  { number: 65, name: 'الطلاق', versesCount: 12, startPage: 558, type: 'مدنية' },
  { number: 66, name: 'التحريم', versesCount: 12, startPage: 560, type: 'مدنية' },
  { number: 67, name: 'الملك', versesCount: 30, startPage: 562, type: 'مكية' },
  { number: 68, name: 'القلم', versesCount: 52, startPage: 564, type: 'مكية' },
  { number: 69, name: 'الحاقة', versesCount: 52, startPage: 566, type: 'مكية' },
  { number: 70, name: 'المعارج', versesCount: 44, startPage: 568, type: 'مكية' },
  { number: 71, name: 'نوح', versesCount: 28, startPage: 570, type: 'مكية' },
  { number: 72, name: 'الجن', versesCount: 28, startPage: 572, type: 'مكية' },
  { number: 73, name: 'المزمل', versesCount: 20, startPage: 574, type: 'مكية' },
  { number: 74, name: 'المدثر', versesCount: 56, startPage: 575, type: 'مكية' },
  { number: 75, name: 'القيامة', versesCount: 40, startPage: 577, type: 'مكية' },
  { number: 76, name: 'الإنسان', versesCount: 31, startPage: 578, type: 'مدنية' },
  { number: 77, name: 'المرسلات', versesCount: 50, startPage: 580, type: 'مكية' },
  { number: 78, name: 'النبأ', versesCount: 40, startPage: 582, type: 'مكية' },
  { number: 79, name: 'النازعات', versesCount: 46, startPage: 583, type: 'مكية' },
  { number: 80, name: 'عبس', versesCount: 42, startPage: 585, type: 'مكية' },
  { number: 81, name: 'التكوير', versesCount: 29, startPage: 586, type: 'مكية' },
  { number: 82, name: 'الانفطار', versesCount: 19, startPage: 587, type: 'مكية' },
  { number: 83, name: 'المطففين', versesCount: 36, startPage: 587, type: 'مكية' },
  { number: 84, name: 'الانشقاق', versesCount: 25, startPage: 589, type: 'مكية' },
  { number: 85, name: 'البروج', versesCount: 22, startPage: 590, type: 'مكية' },
  { number: 86, name: 'الطارق', versesCount: 17, startPage: 591, type: 'مكية' },
  { number: 87, name: 'الأعلى', versesCount: 19, startPage: 591, type: 'مكية' },
  { number: 88, name: 'الغاشية', versesCount: 26, startPage: 592, type: 'مكية' },
  { number: 89, name: 'الفجر', versesCount: 30, startPage: 593, type: 'مكية' },
  { number: 90, name: 'البلد', versesCount: 20, startPage: 594, type: 'مكية' },
  { number: 91, name: 'الشمس', versesCount: 15, startPage: 595, type: 'مكية' },
  { number: 92, name: 'الليل', versesCount: 21, startPage: 595, type: 'مكية' },
  { number: 93, name: 'الضحى', versesCount: 11, startPage: 596, type: 'مكية' },
  { number: 94, name: 'الشرح', versesCount: 8, startPage: 596, type: 'مكية' },
  { number: 95, name: 'التين', versesCount: 8, startPage: 597, type: 'مكية' },
  { number: 96, name: 'العلق', versesCount: 19, startPage: 597, type: 'مكية' },
  { number: 97, name: 'القدر', versesCount: 5, startPage: 598, type: 'مكية' },
  { number: 98, name: 'البينة', versesCount: 8, startPage: 598, type: 'مدنية' },
  { number: 99, name: 'الزلزلة', versesCount: 8, startPage: 599, type: 'مدنية' },
  { number: 100, name: 'العاديات', versesCount: 11, startPage: 599, type: 'مكية' },
  { number: 101, name: 'القارعة', versesCount: 11, startPage: 600, type: 'مكية' },
  { number: 102, name: 'التكاثر', versesCount: 8, startPage: 600, type: 'مكية' },
  { number: 103, name: 'العصر', versesCount: 3, startPage: 601, type: 'مكية' },
  { number: 104, name: 'الهمزة', versesCount: 9, startPage: 601, type: 'مكية' },
  { number: 105, name: 'الفيل', versesCount: 5, startPage: 601, type: 'مكية' },
  { number: 106, name: 'قريش', versesCount: 4, startPage: 602, type: 'مكية' },
  { number: 107, name: 'الماعون', versesCount: 7, startPage: 602, type: 'مكية' },
  { number: 108, name: 'الكوثر', versesCount: 3, startPage: 602, type: 'مكية' },
  { number: 109, name: 'الكافرون', versesCount: 6, startPage: 603, type: 'مكية' },
  { number: 110, name: 'النصر', versesCount: 3, startPage: 603, type: 'مدنية' },
  { number: 111, name: 'المسد', versesCount: 5, startPage: 603, type: 'مكية' },
  { number: 112, name: 'الإخلاص', versesCount: 4, startPage: 604, type: 'مكية' },
  { number: 113, name: 'الفلق', versesCount: 5, startPage: 604, type: 'مكية' },
  { number: 114, name: 'الناس', versesCount: 6, startPage: 604, type: 'مكية' }
];

export const JUZS = [
  { number: 1, name: 'ألم', startPage: 1 },
  { number: 2, name: 'سيقول', startPage: 22 },
  { number: 3, name: 'تلك الرسل', startPage: 42 },
  { number: 4, name: 'لن تنالوا', startPage: 62 },
  { number: 5, name: 'والمحصنات', startPage: 82 },
  { number: 6, name: 'لا يحب الله', startPage: 102 },
  { number: 7, name: 'وإذا سمعوا', startPage: 121 },
  { number: 8, name: 'ولو أننا', startPage: 142 },
  { number: 9, name: 'قال الملأ', startPage: 162 },
  { number: 10, name: 'واعلموا', startPage: 182 },
  { number: 11, name: 'يعتذرون', startPage: 201 },
  { number: 12, name: 'وما من دابة', startPage: 222 },
  { number: 13, name: 'وما أبرئ', startPage: 242 },
  { number: 14, name: 'ربما', startPage: 262 },
  { number: 15, name: 'سبحان الذي', startPage: 282 },
  { number: 16, name: 'قال ألم', startPage: 302 },
  { number: 17, name: 'اقترب', startPage: 322 },
  { number: 18, name: 'قد أفلح', startPage: 342 },
  { number: 19, name: 'وقال الذين', startPage: 362 },
  { number: 20, name: 'أمّن خلق', startPage: 382 },
  { number: 21, name: 'اتل ما أوحي', startPage: 402 },
  { number: 22, name: 'ومن يقنت', startPage: 422 },
  { number: 23, name: 'وما لي', startPage: 442 },
  { number: 24, name: 'فمن أظلم', startPage: 462 },
  { number: 25, name: 'إليه يرد', startPage: 482 },
  { number: 26, name: 'حم', startPage: 502 },
  { number: 27, name: 'قال فما خطبكم', startPage: 522 },
  { number: 28, name: 'قد سمع الله', startPage: 542 },
  { number: 29, name: 'تبارك', startPage: 562 },
  { number: 30, name: 'عمّ', startPage: 582 }
];

export function getSurahForPage(page: number) {
  for (let i = SURAHS.length - 1; i >= 0; i--) {
    if (page >= SURAHS[i].startPage) return SURAHS[i];
  }
  return SURAHS[0];
}

export function getJuzForPage(page: number) {
  for (let i = JUZS.length - 1; i >= 0; i--) {
    if (page >= JUZS[i].startPage) return JUZS[i];
  }
  return JUZS[0];
}

export const RECITERS = [
  { id: 7, name: 'مشاري العفاسي', englishName: 'Mishary Alafasy' },
  { id: 2, name: 'عبد الباسط عبد الصمد - مرتل', englishName: 'Abdul Basit (Murattal)' },
  { id: 1, name: 'عبد الباسط عبد الصمد - مجود', englishName: 'Abdul Basit (Mujawwad)' },
  { id: 3, name: 'عبد الرحمن السديس', englishName: 'Abdurrahman As-Sudais' },
  { id: 10, name: 'سعود الشريم', englishName: 'Saud Ash-Shuraim' },
  { id: 6, name: 'محمود خليل الحصري', englishName: 'Mahmoud Khalil Al-Husary' },
  { id: 9, name: 'محمد صديق المنشاوي - مرتل', englishName: 'Al-Minshawi (Murattal)' },
  { id: 8, name: 'محمد صديق المنشاوي - مجود', englishName: 'Al-Minshawi (Mujawwad)' }
];

export const TAFSIRS = [
  { id: 14, name: 'تفسير ابن كثير', englishName: 'Ibn Kathir' },
  { id: 15, name: 'تفسير الطبري', englishName: 'Al-Tabari' },
  { id: 91, name: 'تفسير السعدي', englishName: 'As-Saadi' },
  { id: 90, name: 'تفسير القرطبي', englishName: 'Al-Qurtubi' },
  { id: 16, name: 'التفسير الميسر', englishName: 'Al-Muyassar' }
];

export const QURAN_PAGES = 604;

export const getPageImageUrl = (page: number) => `https://dn710202.ca.archive.org/0/items/z_20240806xx/${String(page).padStart(3, '0')}.jpg`;
